#define RDP_LOG_COMPONENT "peer"
#include "logging/RDPLog.h"
#include "protocol/RDPPeer.h"
#include "protocol/RDPSecurity.h"

#include <freerdp/freerdp.h>
#include <freerdp/listener.h>
#include <freerdp/server/rdpgfx.h>
#include <freerdp/server/cliprdr.h>
#include <freerdp/server/rdpsnd.h>
#include <freerdp/server/server-common.h>
#include <freerdp/channels/rdpgfx.h>
#include <freerdp/channels/wtsvc.h>
#include <freerdp/channels/drdynvc.h>
#include <freerdp/crypto/certificate.h>
#include <freerdp/crypto/privatekey.h>
#include <winpr/ssl.h>
#include <winpr/synch.h>
#include <winpr/wtsapi.h>
#include <string.h>
#include <stdlib.h>
#include <pthread.h>

/* TLS material generated by scripts/gen-tls-cert.sh (or the installer). */
#ifndef RDP_CERT_PATH
#define RDP_CERT_PATH "/etc/macos-rdp/server.crt"
#endif
#ifndef RDP_KEY_PATH
#define RDP_KEY_PATH  "/etc/macos-rdp/server.key"
#endif

/* ── Settings ──────────────────────────────────────────────────────────── */

/* Load the server certificate + private key into the peer settings. Without
 * these, the TLS handshake cannot complete and the client aborts with a
 * connection/security error (mstsc 0x904). Returns false if either is missing. */
static bool peer_load_certificate(freerdp_peer *peer) {
    rdpSettings *s = peer->context->settings;

    rdpPrivateKey *key = freerdp_key_new_from_file(RDP_KEY_PATH);
    if (!key) {
        rdp_error("could not load private key %s — run gen-tls-cert.sh", RDP_KEY_PATH);
        return false;
    }
    if (!freerdp_settings_set_pointer_len(s, FreeRDP_RdpServerRsaKey, key, 1)) {
        rdp_error("failed to set server RSA key");
        return false;
    }

    rdpCertificate *cert = freerdp_certificate_new_from_file(RDP_CERT_PATH);
    if (!cert) {
        rdp_error("could not load certificate %s — run gen-tls-cert.sh", RDP_CERT_PATH);
        return false;
    }
    if (!freerdp_settings_set_pointer_len(s, FreeRDP_RdpServerCertificate, cert, 1)) {
        rdp_error("failed to set server certificate");
        return false;
    }

    rdp_verbose("loaded TLS certificate and key");
    return true;
}

static bool peer_apply_settings(freerdp_peer *peer) {
    rdpSettings *s = peer->context->settings;
    /* Only set what we actually use. Every extra setting is dead weight. */
    freerdp_settings_set_bool(s,   FreeRDP_NetworkAutoDetect,       FALSE);
    freerdp_settings_set_bool(s,   FreeRDP_SupportGraphicsPipeline, TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_GfxH264,                 TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_GfxAVC444,               FALSE);
    freerdp_settings_set_bool(s,   FreeRDP_GfxSmallCache,           FALSE);
    freerdp_settings_set_bool(s,   FreeRDP_GfxThinClient,           FALSE);
    freerdp_settings_set_bool(s,   FreeRDP_RemoteFxCodec,           FALSE);
    /* ── Security layer ─────────────────────────────────────────────────────
     * Default build: offer TLS (+ legacy RDP as a fallback) with no
     * authentication — the historically known-good config that lets mstsc
     * negotiate TLS. NLA stays off because it needs NTLM/MD4, which the minimal
     * OpenSSL build omits ("md4 NTLM support not available").
     *
     * NLA build (-DMACOS_RDP_ENABLE_NLA + an OpenSSL legacy provider): when a
     * credential is provisioned in /etc/macos-rdp/credentials, require TLS+NLA
     * and authenticate the client. This single switch gates the channel parsers
     * and the input injector behind authentication. See docs/enabling-nla.md. */
    freerdp_settings_set_bool(s,   FreeRDP_UseRdpSecurityLayer,     FALSE);
#ifdef MACOS_RDP_ENABLE_NLA
    struct rdp_credentials cred;
    if (rdp_security_md4_available() && rdp_security_load_credentials(&cred)) {
        freerdp_settings_set_bool(s,   FreeRDP_RdpSecurity,         FALSE);
        freerdp_settings_set_bool(s,   FreeRDP_TlsSecurity,         TRUE);
        freerdp_settings_set_bool(s,   FreeRDP_NlaSecurity,         TRUE);
        freerdp_settings_set_uint32(s, FreeRDP_TlsSecLevel,         2);
        freerdp_settings_set_uint32(s, FreeRDP_EncryptionLevel,     ENCRYPTION_LEVEL_HIGH);
        freerdp_settings_set_string(s, FreeRDP_Username,            cred.username);
        freerdp_settings_set_string(s, FreeRDP_PasswordHash,        cred.password_hash);
        rdp_info("NLA enabled — authenticating user '%s'", cred.username);
    } else {
        freerdp_settings_set_bool(s,   FreeRDP_RdpSecurity,         TRUE);
        freerdp_settings_set_bool(s,   FreeRDP_TlsSecurity,         TRUE);
        freerdp_settings_set_bool(s,   FreeRDP_NlaSecurity,         FALSE);
        freerdp_settings_set_uint32(s, FreeRDP_TlsSecLevel,         1);
        rdp_error("SECURITY: NLA build active but %s — connections are "
                  "UNAUTHENTICATED; provision /etc/macos-rdp/credentials",
                  rdp_security_md4_available() ? "no credential configured"
                                               : "MD4/NTLM unavailable");
    }
#else
    freerdp_settings_set_bool(s,   FreeRDP_RdpSecurity,             TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_TlsSecurity,             TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_NlaSecurity,             FALSE);
    freerdp_settings_set_uint32(s, FreeRDP_TlsSecLevel,             1);
#endif
    freerdp_settings_set_uint32(s, FreeRDP_ColorDepth,              32);
    freerdp_settings_set_bool(s,   FreeRDP_UnicodeInput,            TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_HasHorizontalWheel,      TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_HasExtendedMouseEvent,   TRUE);
    freerdp_settings_set_bool(s,   FreeRDP_SoundBeepsEnabled,       FALSE);

    /* Refuse the connection if the TLS material is missing rather than
     * proceeding and relying on the handshake to fail later. Proceeding is
     * unsafe: with the legacy RDP security layer also offered, a client could
     * negotiate a path that does not require the server certificate at all. */
    if (!peer_load_certificate(peer)) {
        rdp_error("refusing connection: TLS certificate/key unavailable — run gen-tls-cert.sh");
        return false;
    }
    rdp_debug("peer settings applied");
    return true;
}

/* ── Context lifecycle ─────────────────────────────────────────────────── */

static BOOL context_new(freerdp_peer *peer, rdpContext *ctx) {
    RDPPeerContext *c = (RDPPeerContext *)ctx;
    /* Open the Virtual Channel Manager — all dynamic channels live under it. */
    c->vcm = WTSOpenServerA((LPSTR)peer->context);
    if (!c->vcm || c->vcm == INVALID_HANDLE_VALUE) {
        rdp_error("WTSOpenServerA failed");
        return FALSE;
    }
    rdp_debug("VCM opened");
    return TRUE;
}

static void context_free(freerdp_peer *peer, rdpContext *ctx) {
    (void)peer;
    RDPPeerContext *c = (RDPPeerContext *)ctx;
    if (c->gfx)    { rdpgfx_server_context_free(c->gfx);    c->gfx    = NULL; }
    if (c->cliprdr){ cliprdr_server_context_free(c->cliprdr);c->cliprdr= NULL; }
    if (c->rdpsnd) { rdpsnd_server_context_free(c->rdpsnd);  c->rdpsnd = NULL; }
    if (c->vcm)    { WTSCloseServer(c->vcm);                 c->vcm    = NULL; }
    if (c->clipData) { free(c->clipData); c->clipData = NULL; c->clipLen = 0; }
    rdp_debug("peer context freed");
}

/* ── Input callbacks ───────────────────────────────────────────────────── */

static BOOL peer_keyboard(rdpInput *input, UINT16 flags, UINT8 code) {
    RDPPeerContext *ctx = (RDPPeerContext *)input->context;
    if (ctx->callbacks.onKeyboard)
        ctx->callbacks.onKeyboard(ctx->callbacks.userdata, flags, code);
    return TRUE;
}

static BOOL peer_mouse(rdpInput *input, UINT16 flags, UINT16 x, UINT16 y) {
    RDPPeerContext *ctx = (RDPPeerContext *)input->context;
    if (ctx->callbacks.onMouse)
        ctx->callbacks.onMouse(ctx->callbacks.userdata, flags, x, y);
    return TRUE;
}

static BOOL peer_mouse_ex(rdpInput *input, UINT16 flags, UINT16 x, UINT16 y) {
    RDPPeerContext *ctx = (RDPPeerContext *)input->context;
    if (ctx->callbacks.onMouseEx)
        ctx->callbacks.onMouseEx(ctx->callbacks.userdata, flags, x, y);
    return TRUE;
}

/* ── GFX caps negotiation ──────────────────────────────────────────────── */

static UINT gfx_caps_advertise(RdpgfxServerContext *gfx,
                                const RDPGFX_CAPS_ADVERTISE_PDU *pdu) {
    RDPPeerContext *ctx = (RDPPeerContext *)gfx->custom;
    rdp_verbose("GFX caps advertise: %u sets", pdu->capsSetCount);

    /* Stack-allocate the capset — capsSet is a pointer in 3.x. */
    RDPGFX_CAPSET capset = {0};
    RDPGFX_CAPS_CONFIRM_PDU confirm = {0};
    confirm.capsSet = &capset;

    /* Walk advertised caps: prefer 8.x (has AVC420), skip anything lower. */
    for (UINT16 i = 0; i < pdu->capsSetCount; i++) {
        rdp_debug("  caps[%u] version=0x%08x flags=0x%08x",
                  i, pdu->capsSets[i].version, pdu->capsSets[i].flags);
        if (pdu->capsSets[i].version >= RDPGFX_CAPVERSION_8) {
            capset.version = pdu->capsSets[i].version;
            capset.flags   = pdu->capsSets[i].flags;
            break;
        }
    }
    if (!capset.version) {
        rdp_error("client advertised no usable GFX caps version");
        return ERROR_INTERNAL_ERROR;
    }
    rdp_verbose("GFX confirming version=0x%08x flags=0x%08x",
                capset.version, capset.flags);

    UINT rc = gfx->CapsConfirm(gfx, &confirm);
    if (rc != CHANNEL_RC_OK) { rdp_error("CapsConfirm failed: %u", rc); return rc; }

    rdpSettings *s = ctx->base.peer->context->settings;
    UINT32 w = freerdp_settings_get_uint32(s, FreeRDP_DesktopWidth);
    UINT32 h = freerdp_settings_get_uint32(s, FreeRDP_DesktopHeight);

    RDPGFX_CREATE_SURFACE_PDU cs = {0};
    cs.surfaceId   = ctx->surfaceId;
    cs.width       = (UINT16)w;
    cs.height      = (UINT16)h;
    cs.pixelFormat = GFX_PIXEL_FORMAT_XRGB_8888;
    gfx->CreateSurface(gfx, &cs);

    RDPGFX_MAP_SURFACE_TO_OUTPUT_PDU ms = {0};
    ms.surfaceId     = ctx->surfaceId;
    ms.outputOriginX = 0;
    ms.outputOriginY = 0;
    gfx->MapSurfaceToOutput(gfx, &ms);

    ctx->gfxReady = true;
    rdp_info("GFX pipeline ready (%ux%u AVC420)", w, h);
    return CHANNEL_RC_OK;
}

/* ── Clipboard callbacks ───────────────────────────────────────────────── */

static UINT cliprdr_client_format_list(CliprdrServerContext *cliprdr,
                                        const CLIPRDR_FORMAT_LIST *list) {
    rdp_verbose("clipboard: client advertised %u formats", list->numFormats);
    CLIPRDR_FORMAT_LIST_RESPONSE resp = {0};
    resp.common.msgFlags = CB_RESPONSE_OK;
    cliprdr->ServerFormatListResponse(cliprdr, &resp);
    return CHANNEL_RC_OK;
}

static UINT cliprdr_client_format_data(CliprdrServerContext *cliprdr,
                                        const CLIPRDR_FORMAT_DATA_RESPONSE *resp) {
    RDPPeerContext *ctx = (RDPPeerContext *)cliprdr->custom;
    if ((resp->common.msgFlags & CB_RESPONSE_OK) && ctx->callbacks.onClipboard) {
        rdp_verbose("clipboard: %u bytes from client", resp->common.dataLen);
        ctx->callbacks.onClipboard(ctx->callbacks.userdata,
                                   resp->requestedFormatData,
                                   resp->common.dataLen,
                                   CF_UNICODETEXT);
    }
    return CHANNEL_RC_OK;
}

/* Client pasted: it requests the bytes for a format we advertised. Reply with
 * the held host data (or an empty failure response if we have none). */
static UINT cliprdr_client_format_data_request(
        CliprdrServerContext *cliprdr,
        const CLIPRDR_FORMAT_DATA_REQUEST *req) {
    RDPPeerContext *ctx = (RDPPeerContext *)cliprdr->custom;
    CLIPRDR_FORMAT_DATA_RESPONSE resp = {0};

    if (ctx->clipData && ctx->clipLen > 0) {
        resp.common.msgFlags     = CB_RESPONSE_OK;
        resp.common.dataLen      = (UINT32)ctx->clipLen;
        resp.requestedFormatData = (BYTE *)ctx->clipData;
        rdp_verbose("clipboard: serving %zu bytes for format 0x%08x",
                    ctx->clipLen, req->requestedFormatId);
    } else {
        resp.common.msgFlags = CB_RESPONSE_FAIL;
        rdp_verbose("clipboard: data request but nothing held");
    }
    cliprdr->ServerFormatDataResponse(cliprdr, &resp);
    return CHANNEL_RC_OK;
}

/* ── Audio activated callback ──────────────────────────────────────────── */

static void rdpsnd_activated(RdpsndServerContext *rdpsnd) {
    RDPPeerContext *ctx = (RDPPeerContext *)rdpsnd->data;
    /* Pick the first mutually-supported PCM format. */
    for (size_t i = 0; i < rdpsnd->num_client_formats; i++) {
        for (size_t j = 0; j < rdpsnd->num_server_formats; j++) {
            if (audio_format_compatible(&rdpsnd->server_formats[j],
                                        &rdpsnd->client_formats[i])) {
                rdpsnd->SelectFormat(rdpsnd, (UINT16)i);
                ctx->audioReady = true;
                rdp_verbose("audio format negotiated (client idx %zu)", i);
                return;
            }
        }
    }
    rdp_verbose("no compatible audio format found");
}

/* ── PostConnect: open virtual channels ───────────────────────────────── */

static BOOL peer_post_connect(freerdp_peer *peer) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    rdp_verbose("post-connect: opening virtual channels");

    /* GFX is a DYNAMIC virtual channel: it can only be opened once drdynvc has
     * reached DRDYNVC_STATE_READY, which does NOT happen until after PostConnect.
     * Opening here fails with "WTSVirtualChannelOpenEx failed" and the client
     * gets no video (black screen). Create the context now; defer Open() to the
     * run loop, which opens it when drdynvc is ready. */
    ctx->gfx = rdpgfx_server_context_new(ctx->vcm);
    if (!ctx->gfx) { rdp_error("rdpgfx_server_context_new failed"); return FALSE; }
    ctx->gfx->custom        = ctx;
    ctx->gfx->CapsAdvertise = gfx_caps_advertise;
    ctx->surfaceId          = 1;
    rdp_verbose("GFX context created; open deferred until drdynvc ready");

    /* Clipboard. */
    ctx->cliprdr = cliprdr_server_context_new(ctx->vcm);
    if (ctx->cliprdr) {
        ctx->cliprdr->custom                   = ctx;
        ctx->cliprdr->rdpcontext               = peer->context;
        ctx->cliprdr->ClientFormatList         = cliprdr_client_format_list;
        ctx->cliprdr->ClientFormatDataResponse = cliprdr_client_format_data;
        ctx->cliprdr->ClientFormatDataRequest  = cliprdr_client_format_data_request;
        ctx->cliprdr->useLongFormatNames       = TRUE;
        if (ctx->cliprdr->Open(ctx->cliprdr) != CHANNEL_RC_OK) {
            rdp_verbose("clipboard channel open failed");
            cliprdr_server_context_free(ctx->cliprdr);
            ctx->cliprdr = NULL;
        } else { rdp_verbose("clipboard channel opened"); }
    }

    /* Audio. Advertise ONLY raw PCM matching what AudioCapture produces
     * (48 kHz, stereo, signed 16-bit). server_rdpsnd_get_formats would also
     * offer compressed codecs (AAC/ADPCM/GSM); if one were negotiated, our
     * raw-PCM SendSamples would feed the client undecodable garbage.
     * Must be heap-allocated: rdpsnd_server_context_free() calls free() on
     * server_formats, so a static array would crash on teardown. */
    ctx->rdpsnd = rdpsnd_server_context_new(ctx->vcm);
    if (ctx->rdpsnd) {
        AUDIO_FORMAT *pcm = (AUDIO_FORMAT *)calloc(1, sizeof(AUDIO_FORMAT));
        if (pcm) {
            pcm->wFormatTag      = WAVE_FORMAT_PCM;
            pcm->nChannels       = 2;
            pcm->nSamplesPerSec  = 48000;
            pcm->nAvgBytesPerSec = 48000 * 2 * 2;
            pcm->nBlockAlign     = 2 * 2;
            pcm->wBitsPerSample  = 16;
        }
        ctx->rdpsnd->data               = ctx;
        ctx->rdpsnd->Activated          = rdpsnd_activated;
        ctx->rdpsnd->server_formats     = pcm;
        ctx->rdpsnd->num_server_formats = pcm ? 1 : 0;
        ctx->rdpsnd->src_format         = pcm;
        if (ctx->rdpsnd->Initialize(ctx->rdpsnd, TRUE) != CHANNEL_RC_OK) {
            rdp_verbose("audio channel init failed");
            rdpsnd_server_context_free(ctx->rdpsnd);
            ctx->rdpsnd = NULL;
        } else { rdp_verbose("audio channel opened"); }
    }

    return TRUE;
}

static BOOL peer_activate(freerdp_peer *peer) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    ctx->activated = true;
    rdpSettings *s = peer->context->settings;
    UINT32 w = freerdp_settings_get_uint32(s, FreeRDP_DesktopWidth);
    UINT32 h = freerdp_settings_get_uint32(s, FreeRDP_DesktopHeight);
    UINT32 d = freerdp_settings_get_uint32(s, FreeRDP_ColorDepth);
    rdp_info("peer activated: %ux%u @%ubpp", w, h, d);
    if (ctx->callbacks.onReady)
        ctx->callbacks.onReady(ctx->callbacks.userdata, w, h, d);
    return TRUE;
}

/* ── Public API ────────────────────────────────────────────────────────── */

/* Register FreeRDP's built-in server WTS implementation exactly once, before
 * the first WTSOpenServerA. Without this, WinPR's WTS layer tries to dlopen the
 * external FreeRDS plugin (libfreerds-fdsapi.so, Linux-only, absent on macOS),
 * WTSOpenServerA returns NULL, and every connection dies in context_new with
 * "ContextNew callback failed". The sample server does the same (sfreerdp.c).
 *
 * FreeRDP_InitWtsApi is exported by libfreerdp-server but only declared in an
 * internal header the public SDK does not ship, so we forward-declare it. The
 * signature matches WinPR's INIT_WTSAPI_FN typedef. */
extern const WtsApiFunctionTable *FreeRDP_InitWtsApi(void);

static pthread_once_t g_wts_once = PTHREAD_ONCE_INIT;
static void register_freerdp_wts(void) {
    WTSRegisterWtsApiFunctionTable(FreeRDP_InitWtsApi());
}

freerdp_peer *rdp_peer_create(int fd, const RDPPeerCallbacks *callbacks) {
    winpr_InitializeSSL(WINPR_SSL_INIT_DEFAULT);
    rdp_security_init_crypto(); /* activates NTLM/MD4; no-op unless built with NLA */
    pthread_once(&g_wts_once, register_freerdp_wts);
    rdp_verbose("creating peer for fd=%d", fd);

    freerdp_peer *peer = freerdp_peer_new(fd);
    if (!peer) { rdp_error("freerdp_peer_new failed"); return NULL; }

    /* ContextSize (PascalCase in 3.x) replaces context_size. */
    peer->ContextSize  = sizeof(RDPPeerContext);
    peer->ContextNew   = context_new;
    peer->ContextFree  = context_free;

    if (!freerdp_peer_context_new(peer)) {
        rdp_error("freerdp_peer_context_new failed");
        freerdp_peer_free(peer);
        return NULL;
    }

    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    if (callbacks) ctx->callbacks = *callbacks;

    if (!peer_apply_settings(peer)) {
        rdp_error("peer_apply_settings failed");
        freerdp_peer_context_free(peer);
        freerdp_peer_free(peer);
        return NULL;
    }
    peer->PostConnect = peer_post_connect;
    peer->Activate    = peer_activate;

    /* Input is on rdpContext, not on freerdp_peer in 3.x. */
    peer->context->input->KeyboardEvent      = peer_keyboard;
    peer->context->input->MouseEvent         = peer_mouse;
    peer->context->input->ExtendedMouseEvent = peer_mouse_ex;

    if (!peer->Initialize(peer)) {
        rdp_error("peer Initialize failed (TLS handshake error)");
        freerdp_peer_context_free(peer);
        freerdp_peer_free(peer);
        return NULL;
    }

    rdp_verbose("peer initialized");
    return peer;
}

void rdp_peer_destroy(freerdp_peer *peer) {
    if (!peer) return;
    rdp_verbose("destroying peer");
    freerdp_peer_context_free(peer);
    freerdp_peer_free(peer);
}

/*
 * Event-driven run: waits on peer transport handles + VCM channel event
 * rather than spinning. Blocks up to 50ms then returns — caller checks
 * disconnect flag. This replaces the busy-poll loop with proper WaitForMultiple.
 */
bool rdp_peer_run_once(freerdp_peer *peer) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;

    HANDLE events[68] = {0};
    DWORD  nCount = 0;

    /* Peer transport events (typically 1-2 handles). */
    DWORD n = peer->GetEventHandles(peer, events, 64);
    if (n == 0) { rdp_error("GetEventHandles returned 0"); return false; }
    nCount += n;

    /* VCM channel event (drdynvc, cliprdr, etc.). */
    HANDLE vcmEvent = WTSVirtualChannelManagerGetEventHandle(ctx->vcm);
    if (vcmEvent) events[nCount++] = vcmEvent;

    /* GFX channel event (only once the DVC is actually open). */
    if (ctx->gfx && ctx->gfxOpened) {
        HANDLE gfxEvent = rdpgfx_server_get_event_handle(ctx->gfx);
        if (gfxEvent) events[nCount++] = gfxEvent;
    }

    DWORD status = WaitForMultipleObjects(nCount, events, FALSE, 50 /*ms*/);
    if (status == WAIT_FAILED) {
        rdp_error("WaitForMultipleObjects failed");
        return false;
    }

    /* Process peer transport data. */
    if (!peer->CheckFileDescriptor(peer)) {
        rdp_verbose("peer transport closed");
        return false;
    }

    /* Dispatch any pending virtual channel messages. This also advances the
     * drdynvc state machine toward READY. */
    if (vcmEvent && WaitForSingleObject(vcmEvent, 0) == WAIT_OBJECT_0) {
        if (!WTSVirtualChannelManagerCheckFileDescriptor(ctx->vcm)) {
            rdp_error("VCM check failed");
            return false;
        }
    }

    /* Open the GFX dynamic virtual channel once drdynvc is READY. GFX cannot be
     * opened in PostConnect (drdynvc isn't up yet) — doing it here is how the
     * shadow server brings up DVCs. Without this the client gets no video. */
    if (ctx->gfx && !ctx->gfxOpened &&
        WTSVirtualChannelManagerGetDrdynvcState(ctx->vcm) == DRDYNVC_STATE_READY) {
        if (ctx->gfx->Open(ctx->gfx)) {
            ctx->gfxOpened = true;
            rdp_info("GFX channel opened (drdynvc ready)");
        } else {
            rdp_error("GFX Open failed despite drdynvc ready");
        }
    }

    /* Drain GFX channel messages once the channel is open. */
    if (ctx->gfx && ctx->gfxOpened) {
        HANDLE gfxEvent = rdpgfx_server_get_event_handle(ctx->gfx);
        if (gfxEvent && WaitForSingleObject(gfxEvent, 0) == WAIT_OBJECT_0)
            rdpgfx_server_handle_messages(ctx->gfx);
    }

    return true;
}

bool rdp_peer_send_h264_frame(freerdp_peer *peer,
                               const uint8_t *data, size_t len,
                               uint32_t width, uint32_t height,
                               bool isKeyFrame,
                               uint16_t dirtyX, uint16_t dirtyY,
                               uint16_t dirtyW, uint16_t dirtyH) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    if (!ctx->gfxReady || !ctx->gfx) { rdp_debug("gfx not ready"); return false; }

    /* Build the damage region. Keyframes refresh the whole surface, so they
     * must claim the full extent; inter-frames claim only the dirty rect.
     * Align to 16px macroblock boundaries and clamp to surface bounds — the
     * AVC420 region must lie within the decoded picture or the client rejects it. */
    RECTANGLE_16 rect;
    if (isKeyFrame || dirtyW == 0 || dirtyH == 0) {
        rect.left = 0; rect.top = 0;
        rect.right = (UINT16)width; rect.bottom = (UINT16)height;
    } else {
        uint32_t left   = dirtyX & ~15u;                 /* round down to 16 */
        uint32_t top    = dirtyY & ~15u;
        uint32_t right  = (dirtyX + dirtyW + 15u) & ~15u; /* round up to 16 */
        uint32_t bottom = (dirtyY + dirtyH + 15u) & ~15u;
        if (right  > width)  right  = width;
        if (bottom > height) bottom = height;
        if (left   >= right)  { left = 0; right = (uint32_t)width; }
        if (top    >= bottom) { top = 0;  bottom = (uint32_t)height; }
        rect.left = (UINT16)left;  rect.top = (UINT16)top;
        rect.right = (UINT16)right; rect.bottom = (UINT16)bottom;
    }

    /* quantQualityVals MUST be a valid parallel array — the server serializer
     * dereferences quantQualityVals[i] for every region rect. NULL crashes.
     * qp is a quality hint (QoE only, not decode-critical); qualityVal mirrors
     * FreeRDP's own encoder: 100 - (qp & 0x3F). */
    RDPGFX_H264_QUANT_QUALITY quant = {0};
    quant.qp         = 26;
    quant.qualityVal = (BYTE)(100 - (26 & 0x3F));

    RDPGFX_AVC420_BITMAP_STREAM avc = {0};
    avc.data                  = (BYTE *)data;
    avc.length                = (UINT32)len;
    avc.meta.numRegionRects   = 1;
    avc.meta.regionRects      = &rect;
    avc.meta.quantQualityVals = &quant;

    /* The H.264 picture is full-surface, so the destination extent is too. */
    RDPGFX_SURFACE_COMMAND cmd = {0};
    cmd.surfaceId = ctx->surfaceId;
    cmd.codecId   = RDPGFX_CODECID_AVC420;
    cmd.format    = GFX_PIXEL_FORMAT_XRGB_8888;
    cmd.right     = (UINT16)width;
    cmd.bottom    = (UINT16)height;
    cmd.length    = (UINT32)len;
    cmd.data      = (BYTE *)data;
    cmd.extra     = &avc;

    UINT rc = ctx->gfx->SurfaceCommand(ctx->gfx, &cmd);
    if (rc != CHANNEL_RC_OK) { rdp_error("SurfaceCommand failed: %u", rc); return false; }
    rdp_debug("sent %s frame: region=(%u,%u)-(%u,%u) len=%zu",
              isKeyFrame ? "key" : "delta",
              rect.left, rect.top, rect.right, rect.bottom, len);
    return true;
}

bool rdp_peer_send_bitmap(freerdp_peer *peer,
                           const uint8_t *bgra, uint32_t x, uint32_t y,
                           uint32_t width, uint32_t height) {
    rdpUpdate *update = peer->context->update;
    SURFACE_BITS_COMMAND cmd = {0};
    cmd.destLeft             = (UINT16)x;
    cmd.destTop              = (UINT16)y;
    cmd.destRight            = (UINT16)(x + width);
    cmd.destBottom           = (UINT16)(y + height);
    cmd.bmp.bpp              = 32;
    cmd.bmp.width            = (UINT16)width;
    cmd.bmp.height           = (UINT16)height;
    cmd.bmp.bitmapData       = (BYTE *)bgra;
    cmd.bmp.bitmapDataLength = width * height * 4;
    cmd.bmp.codecID          = RDP_CODEC_ID_NONE;
    return update->SurfaceBits(update->context, &cmd);
}

bool rdp_peer_send_audio(freerdp_peer *peer,
                          const int16_t *samples, uint32_t frame_count) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    if (!ctx->rdpsnd || !ctx->audioReady) return false;
    /* SendSamples(context, buf, nframes, timestamp) — real 3.x signature. */
    return ctx->rdpsnd->SendSamples(ctx->rdpsnd, samples, frame_count, 0)
           == CHANNEL_RC_OK;
}

bool rdp_peer_send_clipboard(freerdp_peer *peer,
                              const uint8_t *data, size_t len,
                              uint32_t format) {
    RDPPeerContext *ctx = (RDPPeerContext *)peer->context;
    if (!ctx->cliprdr) { rdp_verbose("no clipboard channel"); return false; }

    /* Store an owned copy of the host clipboard; we hand it to the client only
     * when it sends a Format Data Request. Advertising data unsolicited (the
     * old behaviour) violates MS-RDPECLIP and clients ignore it. */
    free(ctx->clipData);
    ctx->clipData = (uint8_t *)malloc(len);
    if (!ctx->clipData) { ctx->clipLen = 0; return false; }
    memcpy(ctx->clipData, data, len);
    ctx->clipLen    = len;
    ctx->clipFormat = format;

    /* Advertise the available format; the client requests the bytes on paste. */
    CLIPRDR_FORMAT fmt   = { .formatId = (UINT32)format, .formatName = NULL };
    CLIPRDR_FORMAT_LIST list = {0};
    list.common.msgFlags = CB_RESPONSE_OK;
    list.numFormats      = 1;
    list.formats         = &fmt;
    ctx->cliprdr->ServerFormatList(ctx->cliprdr, &list);
    rdp_verbose("clipboard: advertised format 0x%08x (%zu bytes held)", format, len);
    return true;
}
