#!/usr/bin/env bash
# Provision the RDP authentication credential used by NLA.
#
# Stores only the NTLM hash (MD4 of the UTF-16LE password) in
# /etc/macos-rdp/credentials (mode 0600, root-owned) — the plaintext password is
# never written to disk. See docs/enabling-nla.md.
#
# Usage:  sudo ./scripts/set-rdp-credentials.sh [username]
set -euo pipefail

CRED_DIR="/etc/macos-rdp"
CRED_FILE="${CRED_DIR}/credentials"

if [[ "${EUID}" -ne 0 ]]; then
    echo "error: must run as root (the credentials file is root-only)." >&2
    exit 1
fi

# Compute the NTLM hash with a self-contained MD4 so this works regardless of
# whether the host's openssl/python ships MD4 (OpenSSL 3.x hides it in the
# legacy provider). Verified against the standard NTLM test vectors at startup.
ntlm_hash() {
    python3 - "$1" <<'PY'
import sys, struct

def _rol(x, c): return ((x << c) | (x >> (32 - c))) & 0xFFFFFFFF

def md4(msg: bytes) -> bytes:
    A, B, C, D = 0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476
    bits = (8 * len(msg)) & 0xFFFFFFFFFFFFFFFF
    msg += b'\x80'
    while len(msg) % 64 != 56:
        msg += b'\x00'
    msg += struct.pack('<Q', bits)
    F = lambda x, y, z: (x & y) | (~x & z)
    G = lambda x, y, z: (x & y) | (x & z) | (y & z)
    H = lambda x, y, z: x ^ y ^ z
    m = 0xFFFFFFFF
    for off in range(0, len(msg), 64):
        X = list(struct.unpack('<16I', msg[off:off + 64]))
        a, b, c, d = A, B, C, D
        for i in range(4):
            k = 4 * i
            a = _rol((a + F(b, c, d) + X[k]) & m, 3)
            d = _rol((d + F(a, b, c) + X[k + 1]) & m, 7)
            c = _rol((c + F(d, a, b) + X[k + 2]) & m, 11)
            b = _rol((b + F(c, d, a) + X[k + 3]) & m, 19)
        for i in range(4):
            a = _rol((a + G(b, c, d) + X[i] + 0x5a827999) & m, 3)
            d = _rol((d + G(a, b, c) + X[i + 4] + 0x5a827999) & m, 5)
            c = _rol((c + G(d, a, b) + X[i + 8] + 0x5a827999) & m, 9)
            b = _rol((b + G(c, d, a) + X[i + 12] + 0x5a827999) & m, 13)
        for i in (0, 2, 1, 3):
            a = _rol((a + H(b, c, d) + X[i] + 0x6ed9eba1) & m, 3)
            d = _rol((d + H(a, b, c) + X[i + 8] + 0x6ed9eba1) & m, 9)
            c = _rol((c + H(d, a, b) + X[i + 4] + 0x6ed9eba1) & m, 11)
            b = _rol((b + H(c, d, a) + X[i + 12] + 0x6ed9eba1) & m, 15)
        A = (A + a) & m; B = (B + b) & m; C = (C + c) & m; D = (D + d) & m
    return struct.pack('<4I', A, B, C, D)

def ntlm(pw: str) -> str:
    return md4(pw.encode('utf-16-le')).hex()

# Self-test against the canonical NTLM vectors; abort if the MD4 is wrong.
assert ntlm("") == "31d6cfe0d16ae931b73c59d7e0c089c0"
assert ntlm("password") == "8846f7eaee8fb117ad06bdd830b7586c"

sys.stdout.write(ntlm(sys.argv[1]))
PY
}

USERNAME="${1:-}"
if [[ -z "${USERNAME}" ]]; then
    read -r -p "RDP username: " USERNAME
fi
if [[ -z "${USERNAME}" ]]; then
    echo "error: username must not be empty." >&2
    exit 1
fi

read -r -s -p "RDP password: " PASSWORD; echo
read -r -s -p "Confirm password: " PASSWORD2; echo
if [[ "${PASSWORD}" != "${PASSWORD2}" ]]; then
    echo "error: passwords do not match." >&2
    exit 1
fi
if [[ -z "${PASSWORD}" ]]; then
    echo "error: empty password not allowed." >&2
    exit 1
fi

HASH="$(ntlm_hash "${PASSWORD}")"
unset PASSWORD PASSWORD2

mkdir -p "${CRED_DIR}"
chmod 700 "${CRED_DIR}"

umask 177
cat > "${CRED_FILE}" <<EOF
# macos-rdp NLA credential — generated by set-rdp-credentials.sh
# Contains only the NTLM hash (MD4 of UTF-16LE password), never the plaintext.
username=${USERNAME}
passwordhash=${HASH}
EOF
chmod 600 "${CRED_FILE}"
chown root:wheel "${CRED_FILE}" 2>/dev/null || true

echo "Wrote ${CRED_FILE} for user '${USERNAME}'."
echo "Restart the daemon and connect with NLA (mstsc / xfreerdp /sec:nla)."
echo "Note: NLA is only enforced in a build configured with -DMACOS_RDP_ENABLE_NLA"
echo "      and an OpenSSL that exposes the legacy provider (see docs/enabling-nla.md)."
